log:
  level:
    global: debug
  path: '/Users/eironn/logs'
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: '123456'
    url: jdbc:mysql://localhost:3306/third?stringtype=unspecified&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      minIdle: 50
      maxActive: 100
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      query-timeout: 1000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      use-global-data-source-stat: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dm.sync.entity.po.*
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #驼峰下划线转换
      #      column-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false